### ISSUE TITLE
Optimizing Docker-related files and images

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [hackla-engage/engage-backend#170]
Hi there,

I don't know how much you are using Docker containers in this project, but I believe that using Docker containers improve the developer happiness since they don't need to install and configure every single component that the project requires.

# Files

`docker-compose.yml` and `Dockerfile` contains large Debian images, for example, PostgreSQL, Redis, and Python images. Debian does a great job to provide a huge toolset out of the box.

## `docker-compose.yml`

Docker Compose files generally suit for setting up containers in development, testing or CI. Some properties like `work_dir_path` and `entrypoint` can be set in a `Dockerfile` on the container stage; therefore, we can keep the `docker-compose.yml` as simple as we can, and also, Dockerfile can be used in different stages without adding a flag.

## `Dockerfile`

The project's `Dockerfile` uses `python:3.6.5` image which is large Debian image (912MB on disk). Debian provides a variety of different tools, but the main concept of a container is **do one thing and do it well** even if you are using the container for development purpose.

I see two comments on the `Dockerfile`

* Expose is NOT supported by Heroku
* Run the image as a non-root

I heard that you are not running Heroku anymore, so I skip that. Running a container with non-root user account is a good practice since root users can do everything[<sup>1</sup>](https://stackoverflow.com/a/19056603/8929392) inside the container and outside of the container[<sup>2</sup>](https://stackoverflow.com/a/24290239/8929392).

### The purpose of Docker container

`runservices.sh` does the magic with installing Python dependencies, running the migration and seeding the PostgreSQL after these, it runs the application server. So, if go back to UNIX philosophy, the script is doing something wrong, and also, it adds additional time on CI.

Thank you

**Comment by eselkin** [comment]
I'm not sure what the purpose of this issue is. 
The docker setup here is for testing and is not used currently for deployment!

The size of the container matters minimally in its current form.
The Dockerfile could be cut down to using a smaller image, but we're trying to restrict to a specific python version that is sometimes not available on some distributions.

The Dockerfile does not need those comments. They are no longer important.

The runservices.sh script is not doing anything "wrong" it is just doing too much if it were for a "deployment" scenario. If it were being used in deployment (which that script is not) it would be doing too much that should have already been completed by the Dockerfile.

If this setup were to be used in deployment we'd have the image be built in CD

**Comment by BerkhanBerkdemir** [comment]
> I'm not sure what the purpose of this issue is.

A way to make a Docker development environment and decreasing the CI time.

>  The Dockerfile could be cut down to using a smaller image, but we're trying to restrict to a specific python version that is sometimes not available on some distributions.

The official image has Debian, Debian (`slim`) and Alpine distributions. Before posting this issue, I run tests with `python:3.6.5-alpine` image.

Anyway. I can clearly see that you use Docker on CircleCI, and there is no plan or user that uses Docker for development purpose.

Thank you for reviewing that issue, @eselkin.

**Comment by eselkin** [comment]
Yes, we can use any of the python 3.6.5 images. You can make a PR for that change, of course
